//! π0-FAST static-FP8 activation calibration profile.
//!
//! A profile binds the measured BF16 activation maxima of one checkpoint to the
//! named sites its FP8 execution plan consumes. It is generated by
//! `scripts/calibrate_pi0fast.py` from representative Observations and read back
//! here before an FP8 runtime is constructed, so a deployment can never run FP8
//! against a scale set that was not measured for its data.
//!
//! This module is CUDA-independent: it owns the plan, the profile contract and
//! checkpoint identity, while [`super::calibration`] owns the BF16 capture that
//! produces the numbers.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use apxinf_core::{Error, Result};
use serde::de::{MapAccess, Visitor};
use serde::{Deserialize, Deserializer};

use super::Pi0FastConfig;
use super::fp8_weights::E4M3_MAX;

pub const CALIBRATION_SCHEMA: &str = "apxinf.pi0fast.fp8-calibration.v1";
pub const FP8_FORMAT: &str = "e4m3fn";
pub const CALIBRATION_STATISTIC: &str = "absmax";
pub const CALIBRATION_SCALE_RULE: &str = "max(amax*margin/448,1e-8)";

/// π0-FAST decodes with a greedy argmax and has no sampler state.
///
/// π0.5 seeds a flow-matching latent per sample, so its profiles name an RNG
/// algorithm. The token decoder is deterministic given the Observation, so the
/// recorded policy is documented as such rather than pretending a seed did
/// anything.
pub const CALIBRATION_SEED_ALGORITHM: &str = "greedy-argmax-deterministic-v1";
pub const CALIBRATION_SEED_SEQUENCE: &str = "[base_seed,sample_index]";

/// Site naming for the two GEMM inputs that are not inside a transformer layer.
pub const MULTIMODAL_PROJECTOR_SITE: &str = "multimodal_projector.input";
pub const LM_HEAD_SITE: &str = "lm_head.input";

/// The four GEMM inputs of one SigLIP vision block.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VisionLayerSites {
    /// Input to `qkv`, i.e. the output of `norm1`.
    pub qkv_input: String,
    /// Input to the attention output projection.
    pub attention_output: String,
    /// Input to `fc1`, i.e. the output of `norm2`.
    pub fc1_input: String,
    /// Input to `fc2`, i.e. the GELU activation.
    pub fc2_input: String,
}

/// The four GEMM inputs of one Gemma language layer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LanguageLayerSites {
    /// Input to `qkv`, i.e. the output of the input RMSNorm.
    pub qkv_input: String,
    /// Input to the attention output projection.
    pub attention_output: String,
    /// Input to `gate_up`, i.e. the post-attention RMSNorm output.
    pub gate_up_input: String,
    /// Input to `down`, i.e. the `gelu(gate) * up` activation.
    pub down_input: String,
}

/// Every activation site the π0-FAST FP8 runtime needs a scale for.
///
/// The order is the execution order, so a coverage failure reads the same way
/// in the generator and in the loader.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pi0FastCalibrationPlan {
    sites: Vec<String>,
    vision_layers: Vec<VisionLayerSites>,
    language_layers: Vec<LanguageLayerSites>,
}

impl Pi0FastCalibrationPlan {
    pub fn for_config(config: &Pi0FastConfig) -> Self {
        let mut sites = Vec::new();
        let vision_layers = (0..config.vision_depth)
            .map(|index| {
                let named = |suffix: &str| format!("vision.layers.{index}.{suffix}");
                VisionLayerSites {
                    qkv_input: named("qkv_input"),
                    attention_output: named("attention_output"),
                    fc1_input: named("fc1_input"),
                    fc2_input: named("fc2_input"),
                }
            })
            .collect::<Vec<_>>();
        for layer in &vision_layers {
            sites.extend([
                layer.qkv_input.clone(),
                layer.attention_output.clone(),
                layer.fc1_input.clone(),
                layer.fc2_input.clone(),
            ]);
        }
        sites.push(MULTIMODAL_PROJECTOR_SITE.to_owned());
        let language_layers = (0..config.language.depth)
            .map(|index| {
                let named = |suffix: &str| format!("language.layers.{index}.{suffix}");
                LanguageLayerSites {
                    qkv_input: named("qkv_input"),
                    attention_output: named("attention_output"),
                    gate_up_input: named("gate_up_input"),
                    down_input: named("down_input"),
                }
            })
            .collect::<Vec<_>>();
        for layer in &language_layers {
            sites.extend([
                layer.qkv_input.clone(),
                layer.attention_output.clone(),
                layer.gate_up_input.clone(),
                layer.down_input.clone(),
            ]);
        }
        sites.push(LM_HEAD_SITE.to_owned());
        Self {
            sites,
            vision_layers,
            language_layers,
        }
    }

    pub fn sites(&self) -> &[String] {
        &self.sites
    }

    pub fn vision_layers(&self) -> &[VisionLayerSites] {
        &self.vision_layers
    }

    pub fn language_layers(&self) -> &[LanguageLayerSites] {
        &self.language_layers
    }
}

#[derive(Debug, Clone)]
pub struct Pi0FastFp8Calibration {
    scales: HashMap<String, f32>,
    warnings: Vec<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CalibrationProfile {
    schema: String,
    model: ProfileModel,
    quantization: ProfileQuantization,
    calibration_data: CalibrationData,
    seed_policy: SeedPolicy,
    source_revision: String,
    device: DeviceSummary,
    plan: ProfilePlan,
    observed_sites: Vec<String>,
    scales: ScaleMap,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ProfileModel {
    family: String,
    checkpoint: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ProfileQuantization {
    format: String,
    statistic: String,
    scale_rule: String,
    margin: f32,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CalibrationData {
    identity: String,
    kind: String,
    production: bool,
    sample_count: usize,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct SeedPolicy {
    algorithm: String,
    base_seed: u64,
    sample_sequence: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct DeviceSummary {
    requested: String,
    host: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ProfilePlan {
    sites: Vec<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ScaleEntry {
    amax: f32,
    scale: f32,
}

struct ScaleMap(BTreeMap<String, ScaleEntry>);

impl<'de> Deserialize<'de> for ScaleMap {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_map(ScaleMapVisitor)
    }
}

struct ScaleMapVisitor;

impl<'de> Visitor<'de> for ScaleMapVisitor {
    type Value = ScaleMap;

    fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("a map of unique π0-FAST calibration sites")
    }

    fn visit_map<M>(self, mut access: M) -> std::result::Result<Self::Value, M::Error>
    where
        M: MapAccess<'de>,
    {
        let mut scales = BTreeMap::new();
        while let Some((site, entry)) = access.next_entry::<String, ScaleEntry>()? {
            if scales.insert(site.clone(), entry).is_some() {
                return Err(serde::de::Error::custom(format!(
                    "duplicate calibration scale site `{site}`"
                )));
            }
        }
        Ok(ScaleMap(scales))
    }
}

impl Pi0FastFp8Calibration {
    pub fn from_json_file(
        path: &Path,
        config: &Pi0FastConfig,
        checkpoint: &str,
    ) -> Result<Self> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| Error::Other(format!("read {}: {e}", path.display())))?;
        let calibration = Self::from_json_str(&raw, config, checkpoint)?;
        for warning in calibration.warnings() {
            eprintln!("warning: {warning}");
        }
        Ok(calibration)
    }

    /// Parse and fully validate a profile before an FP8 runtime is constructed.
    pub fn from_json_str(raw: &str, config: &Pi0FastConfig, checkpoint: &str) -> Result<Self> {
        let profile: CalibrationProfile = serde_json::from_str(raw)
            .map_err(|e| Error::Other(format!("π0-FAST FP8 calibration JSON: {e}")))?;
        if profile.schema != CALIBRATION_SCHEMA {
            return Err(Error::Other(format!(
                "π0-FAST FP8 calibration schema mismatch: expected {CALIBRATION_SCHEMA}, got {}",
                profile.schema
            )));
        }
        if profile.model.family != "pi0fast" {
            return Err(Error::Other(format!(
                "π0-FAST FP8 calibration model family mismatch: {}",
                profile.model.family
            )));
        }
        // A stale profile is a real deployment hazard, but it is the caller's
        // checkpoint choice and the numbers are still dimensionally valid, so
        // this is reported rather than fatal — the same rule π0.5 uses.
        let mut warnings = Vec::new();
        if profile.model.checkpoint != checkpoint {
            warnings.push(format!(
                concat!(
                    "π0-FAST FP8 calibration checkpoint identity mismatch: ",
                    "profile={}, runtime={}; continuing with the supplied profile"
                ),
                profile.model.checkpoint, checkpoint
            ));
        }
        if profile.quantization.format != FP8_FORMAT
            || profile.quantization.statistic != CALIBRATION_STATISTIC
            || profile.quantization.scale_rule != CALIBRATION_SCALE_RULE
        {
            return Err(Error::Other(
                "π0-FAST FP8 calibration quantization contract mismatch".into(),
            ));
        }
        if !profile.quantization.margin.is_finite() || profile.quantization.margin < 1.0 {
            return Err(Error::Other(
                "π0-FAST FP8 calibration has invalid margin".into(),
            ));
        }
        if profile.calibration_data.identity.is_empty()
            || profile.calibration_data.kind.is_empty()
            || profile.calibration_data.sample_count == 0
            || profile.source_revision.is_empty()
            || profile.source_revision == "unknown"
            || profile.device.requested.is_empty()
            || profile.device.host.is_empty()
            || profile.seed_policy.algorithm.is_empty()
            || profile.seed_policy.sample_sequence.is_empty()
        {
            return Err(Error::Other(
                "π0-FAST FP8 calibration manifest is incomplete".into(),
            ));
        }
        match (
            profile.calibration_data.kind.as_str(),
            profile.calibration_data.production,
        ) {
            ("representative", true) | ("synthetic-zero-fixture", false) => {}
            _ => {
                return Err(Error::Other(
                    "π0-FAST FP8 calibration data kind/production label is ambiguous".into(),
                ))
            }
        }
        if profile.calibration_data.identity.starts_with("synthetic:")
            && profile.calibration_data.production
        {
            return Err(Error::Other(
                "π0-FAST FP8 calibration synthetic data cannot be labeled production".into(),
            ));
        }
        if profile.seed_policy.algorithm != CALIBRATION_SEED_ALGORITHM
            || profile.seed_policy.sample_sequence != CALIBRATION_SEED_SEQUENCE
        {
            return Err(Error::Other(
                "π0-FAST FP8 calibration seed policy is incompatible".into(),
            ));
        }
        let _ = profile.seed_policy.base_seed;

        let expected = Pi0FastCalibrationPlan::for_config(config);
        let expected_set = expected.sites().iter().cloned().collect::<BTreeSet<_>>();
        let plan_set = unique_sites("plan", &profile.plan.sites)?;
        let observed_set = unique_sites("observed_sites", &profile.observed_sites)?;
        let scale_set = profile.scales.0.keys().cloned().collect::<BTreeSet<_>>();
        if plan_set != expected_set || observed_set != expected_set || scale_set != expected_set {
            let missing = expected_set
                .difference(&scale_set)
                .take(8)
                .collect::<Vec<_>>();
            let unknown = scale_set
                .difference(&expected_set)
                .take(8)
                .collect::<Vec<_>>();
            return Err(Error::Other(format!(
                "π0-FAST FP8 calibration site coverage is missing, unknown, or \
                 incompatible: missing={missing:?}, unknown={unknown:?}"
            )));
        }

        let mut scales = HashMap::with_capacity(profile.scales.0.len());
        for (name, entry) in profile.scales.0 {
            if !entry.amax.is_finite()
                || entry.amax < 0.0
                || !entry.scale.is_finite()
                || entry.scale <= 0.0
            {
                return Err(Error::Other(format!(
                    "π0-FAST FP8 calibration entry `{name}` is non-finite or non-positive"
                )));
            }
            let expected_scale = ((entry.amax as f64 * profile.quantization.margin as f64)
                / E4M3_MAX as f64)
                .max(1.0e-8);
            if !expected_scale.is_finite()
                || expected_scale > f32::MAX as f64
                || (entry.scale as f64 - expected_scale).abs() > expected_scale * 1.0e-5
            {
                return Err(Error::Other(format!(
                    "π0-FAST FP8 calibration entry `{name}` has ambiguous amax/scale values"
                )));
            }
            scales.insert(name, entry.scale);
        }
        Ok(Self { scales, warnings })
    }

    pub fn scale(&self, name: &str) -> Result<f32> {
        self.scales
            .get(name)
            .copied()
            .ok_or_else(|| Error::Other(format!("missing π0-FAST FP8 activation scale `{name}`")))
    }

    pub fn len(&self) -> usize {
        self.scales.len()
    }

    pub fn is_empty(&self) -> bool {
        self.scales.is_empty()
    }

    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }
}

fn unique_sites(label: &str, sites: &[String]) -> Result<BTreeSet<String>> {
    let set = sites.iter().cloned().collect::<BTreeSet<_>>();
    if set.len() != sites.len() {
        return Err(Error::Other(format!(
            "π0-FAST FP8 calibration {label} contains ambiguous duplicate sites"
        )));
    }
    Ok(set)
}

/// Content identity shared by calibration generation and runtime validation.
///
/// The Python generator in `scripts/calibrate_pi0fast.py` reproduces this byte
/// for byte; `tests/fixtures/checkpoint_identity` pins both sides. It is a
/// model-local copy on purpose: `apxinf-model` families do not import each
/// other's calibration types.
pub fn checkpoint_identity(path: &Path) -> Result<String> {
    let (root, files) = checkpoint_files(path)?;
    if files.is_empty() {
        return Err(Error::Other(format!(
            "checkpoint {} has no safetensors",
            path.display()
        )));
    }
    let mut canonical = files
        .into_iter()
        .map(|file| {
            let relative = file.strip_prefix(&root).map_err(|_| {
                Error::Other(format!(
                    "checkpoint file {} is outside {}",
                    file.display(),
                    root.display()
                ))
            })?;
            let relative = relative
                .components()
                .map(|part| {
                    part.as_os_str().to_str().ok_or_else(|| {
                        Error::Other(format!(
                            "checkpoint path is not canonical UTF-8: {}",
                            file.display()
                        ))
                    })
                })
                .collect::<Result<Vec<_>>>()?
                .join("/");
            Ok((relative, file))
        })
        .collect::<Result<Vec<_>>>()?;
    canonical.sort_by(|left, right| left.0.as_bytes().cmp(right.0.as_bytes()));
    let mut digest = Sha256::new();
    for (relative, file) in canonical {
        digest.update(relative.as_bytes());
        digest.update(&[0]);
        let mut handle = File::open(&file)
            .map_err(|error| Error::Other(format!("read {}: {error}", file.display())))?;
        let mut buffer = [0u8; 1024 * 1024];
        loop {
            let count = handle
                .read(&mut buffer)
                .map_err(|error| Error::Other(format!("read {}: {error}", file.display())))?;
            if count == 0 {
                break;
            }
            digest.update(&buffer[..count]);
        }
    }
    Ok(format!("sha256:{}", digest.finish_hex()))
}

fn checkpoint_files(path: &Path) -> Result<(PathBuf, Vec<PathBuf>)> {
    if path.is_dir() {
        let index = path.join("model.safetensors.index.json");
        let model = path.join("model.safetensors");
        let files = if index.is_file() {
            checkpoint_index_files(&index)?
        } else if model.is_file() {
            vec![model]
        } else {
            let mut files = Vec::new();
            collect_safetensors(path, &mut files)?;
            files
        };
        Ok((path.to_path_buf(), files))
    } else if path
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.ends_with(".index.json"))
    {
        Ok((
            path.parent()
                .unwrap_or_else(|| Path::new("."))
                .to_path_buf(),
            checkpoint_index_files(path)?,
        ))
    } else {
        Ok((
            path.parent()
                .unwrap_or_else(|| Path::new("."))
                .to_path_buf(),
            vec![path.to_path_buf()],
        ))
    }
}

fn checkpoint_index_files(index_path: &Path) -> Result<Vec<PathBuf>> {
    let raw = std::fs::read_to_string(index_path)
        .map_err(|error| Error::Other(format!("read {}: {error}", index_path.display())))?;
    let index: serde_json::Value = serde_json::from_str(&raw)
        .map_err(|error| Error::Other(format!("checkpoint index JSON: {error}")))?;
    let weight_map = index
        .get("weight_map")
        .and_then(|value| value.as_object())
        .ok_or_else(|| Error::Other("checkpoint index has no weight_map".into()))?;
    let mut names = BTreeSet::new();
    for value in weight_map.values() {
        let name = value
            .as_str()
            .ok_or_else(|| Error::Other("checkpoint index has a non-string shard".into()))?;
        let relative = Path::new(name);
        if relative.is_absolute()
            || relative
                .components()
                .any(|part| matches!(part, std::path::Component::ParentDir))
        {
            return Err(Error::Other(format!(
                "checkpoint index has an unsafe shard path: {name}"
            )));
        }
        names.insert(name.to_owned());
    }
    let root = index_path.parent().unwrap_or_else(|| Path::new("."));
    Ok(names.into_iter().map(|name| root.join(name)).collect())
}

fn collect_safetensors(directory: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(directory)
        .map_err(|error| Error::Other(format!("read {}: {error}", directory.display())))?
    {
        let path = entry
            .map_err(|error| Error::Other(error.to_string()))?
            .path();
        if path.is_dir() {
            collect_safetensors(&path, files)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("safetensors") {
            files.push(path);
        }
    }
    Ok(())
}

/// Minimal SHA-256, matching the generator's `hashlib` output.
struct Sha256 {
    state: [u32; 8],
    buffer: Vec<u8>,
    bytes: u64,
}

impl Sha256 {
    fn new() -> Self {
        Self {
            state: [
                0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
                0x5be0cd19,
            ],
            buffer: Vec::with_capacity(64),
            bytes: 0,
        }
    }

    fn update(&mut self, mut input: &[u8]) {
        self.bytes += input.len() as u64;
        if !self.buffer.is_empty() {
            let needed = 64 - self.buffer.len();
            let take = needed.min(input.len());
            self.buffer.extend_from_slice(&input[..take]);
            input = &input[take..];
            if self.buffer.len() == 64 {
                let block: [u8; 64] = self.buffer.as_slice().try_into().unwrap();
                self.compress(&block);
                self.buffer.clear();
            }
        }
        while input.len() >= 64 {
            let block: &[u8; 64] = input[..64].try_into().unwrap();
            self.compress(block);
            input = &input[64..];
        }
        self.buffer.extend_from_slice(input);
    }

    fn finish_hex(mut self) -> String {
        let bit_len = self.bytes * 8;
        self.buffer.push(0x80);
        while self.buffer.len() % 64 != 56 {
            self.buffer.push(0);
        }
        self.buffer.extend_from_slice(&bit_len.to_be_bytes());
        let blocks = std::mem::take(&mut self.buffer);
        for chunk in blocks.chunks_exact(64) {
            self.compress(chunk.try_into().unwrap());
        }
        self.state
            .iter()
            .map(|word| format!("{word:08x}"))
            .collect::<Vec<_>>()
            .join("")
    }

    fn compress(&mut self, block: &[u8; 64]) {
        const K: [u32; 64] = [
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
            0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
            0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
            0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
            0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
            0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
            0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
            0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
            0xc67178f2,
        ];
        let mut words = [0u32; 64];
        for (index, bytes) in block.chunks_exact(4).enumerate() {
            words[index] = u32::from_be_bytes(bytes.try_into().unwrap());
        }
        for index in 16..64 {
            let s0 = words[index - 15].rotate_right(7)
                ^ words[index - 15].rotate_right(18)
                ^ (words[index - 15] >> 3);
            let s1 = words[index - 2].rotate_right(17)
                ^ words[index - 2].rotate_right(19)
                ^ (words[index - 2] >> 10);
            words[index] = words[index - 16]
                .wrapping_add(s0)
                .wrapping_add(words[index - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = self.state;
        for index in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let choose = (e & f) ^ ((!e) & g);
            let t1 = h
                .wrapping_add(s1)
                .wrapping_add(choose)
                .wrapping_add(K[index])
                .wrapping_add(words[index]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let majority = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(majority);
            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (state, value) in self.state.iter_mut().zip([a, b, c, d, e, f, g, h]) {
            *state = state.wrapping_add(value);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> Pi0FastConfig {
        Pi0FastConfig::default()
    }

    fn plan_sites() -> Vec<String> {
        Pi0FastCalibrationPlan::for_config(&config())
            .sites()
            .to_vec()
    }

    fn profile(overrides: impl FnOnce(&mut serde_json::Value)) -> String {
        let sites = plan_sites();
        let mut scales = serde_json::Map::new();
        for site in &sites {
            scales.insert(
                site.clone(),
                serde_json::json!({"amax": 10.0, "scale": 10.0f64 * 1.1 / 448.0}),
            );
        }
        let mut document = serde_json::json!({
            "schema": CALIBRATION_SCHEMA,
            "model": {"family": "pi0fast", "checkpoint": "sha256:test"},
            "quantization": {
                "format": FP8_FORMAT,
                "statistic": CALIBRATION_STATISTIC,
                "scale_rule": CALIBRATION_SCALE_RULE,
                "margin": 1.1
            },
            "calibration_data": {
                "identity": "sha256:dataset",
                "kind": "representative",
                "production": true,
                "sample_count": 10
            },
            "seed_policy": {
                "algorithm": CALIBRATION_SEED_ALGORITHM,
                "base_seed": 0,
                "sample_sequence": CALIBRATION_SEED_SEQUENCE
            },
            "source_revision": "abc123",
            "device": {"requested": "cuda:0", "host": "test-host"},
            "plan": {"sites": sites},
            "observed_sites": plan_sites(),
            "scales": scales,
        });
        overrides(&mut document);
        serde_json::to_string(&document).unwrap()
    }

    #[test]
    fn plan_covers_every_fp8_site_in_execution_order() {
        let config = config();
        let plan = Pi0FastCalibrationPlan::for_config(&config);
        assert_eq!(
            plan.sites().len(),
            config.vision_depth * 4 + config.language.depth * 4 + 2
        );
        assert_eq!(plan.sites()[0], "vision.layers.0.qkv_input");
        assert_eq!(
            plan.sites()[config.vision_depth * 4],
            MULTIMODAL_PROJECTOR_SITE
        );
        assert_eq!(*plan.sites().last().unwrap(), LM_HEAD_SITE);
        assert_eq!(plan.vision_layers().len(), config.vision_depth);
        assert_eq!(plan.language_layers().len(), config.language.depth);
    }

    #[test]
    fn profile_loads_every_scale_and_reports_no_warning() {
        let calibration =
            Pi0FastFp8Calibration::from_json_str(&profile(|_| {}), &config(), "sha256:test")
                .unwrap();
        assert_eq!(calibration.len(), plan_sites().len());
        assert!(calibration.warnings().is_empty());
        assert!(
            (calibration.scale(LM_HEAD_SITE).unwrap() - 10.0 * 1.1 / 448.0).abs() < 1e-9
        );
    }

    #[test]
    fn checkpoint_mismatch_warns_without_blocking_the_load() {
        let calibration =
            Pi0FastFp8Calibration::from_json_str(&profile(|_| {}), &config(), "sha256:other")
                .unwrap();
        assert_eq!(calibration.warnings().len(), 1);
    }

    #[test]
    fn missing_site_coverage_is_rejected() {
        let raw = profile(|document| {
            document["scales"]
                .as_object_mut()
                .unwrap()
                .remove(LM_HEAD_SITE);
        });
        let error = Pi0FastFp8Calibration::from_json_str(&raw, &config(), "sha256:test")
            .unwrap_err()
            .to_string();
        assert!(error.contains("site coverage"), "{error}");
    }

    #[test]
    fn scale_that_does_not_match_its_amax_is_rejected() {
        let raw = profile(|document| {
            document["scales"][LM_HEAD_SITE]["scale"] = serde_json::json!(1.0);
        });
        let error = Pi0FastFp8Calibration::from_json_str(&raw, &config(), "sha256:test")
            .unwrap_err()
            .to_string();
        assert!(error.contains("ambiguous amax/scale"), "{error}");
    }

    #[test]
    fn synthetic_data_cannot_be_labelled_production() {
        let raw = profile(|document| {
            document["calibration_data"]["identity"] = serde_json::json!("synthetic:zero");
        });
        assert!(Pi0FastFp8Calibration::from_json_str(&raw, &config(), "sha256:test").is_err());
    }

    #[test]
    fn a_foreign_family_profile_is_rejected() {
        let raw = profile(|document| {
            document["model"]["family"] = serde_json::json!("pi05");
        });
        assert!(Pi0FastFp8Calibration::from_json_str(&raw, &config(), "sha256:test").is_err());
    }

    #[test]
    fn sha256_matches_the_standard_vector() {
        let mut digest = Sha256::new();
        digest.update(b"abc");
        assert_eq!(
            digest.finish_hex(),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }

    #[test]
    fn checkpoint_identity_matches_the_shared_cross_language_fixture() {
        let fixture = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/checkpoint_identity");
        let expected = std::fs::read_to_string(fixture.join("expected.sha256"))
            .unwrap()
            .trim()
            .to_owned();
        assert_eq!(checkpoint_identity(&fixture).unwrap(), expected);
        assert_eq!(
            checkpoint_identity(&fixture.join("model.safetensors.index.json")).unwrap(),
            expected
        );
    }
}
